package com.example.inventory;

/**
 * Classic Java entry-point file auto-generated by tools like Maven when you create a new project.
 * 
 * Why is this here?
 * - Many project generators (like Maven/IDEA) create this file as an example of a minimal Java app, but for Spring Boot apps, 
 *   we rarely use this App.java as our main entry point.
 * 
 * What does it do?
 * - If you run this directly (java App), it will simply print "Hello World!" to the console.
 * - It does NOT start your Spring Boot application—that’s InventorySystemApplication.java!
 * 
 * What should you take care?
 * - Generally, don’t put any application code here for Spring Boot apps.
 * - Safe to leave it in (for reference/learning), but the real starting point is always your @SpringBootApplication class.
 */
public class App 
{
    /**
     * This is the classic main method required in any standard Java application to start the program.
     * 
     * Here it just prints to the console. For Spring Boot apps, main() is in your InventorySystemApplication.java file instead.
     */
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" ); // Prints a greeting message to the console
    }
}
